Default: &defaults
  user: tete
  password: tete
  host: localhost
  port: 5432
  database: tete
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: tete_test
  <<: *defaults

Staging:
  database: tete_staging
  poolsize: 100
  <<: *defaults
